/**
 * This class is generated by jOOQ
 */
package me.lty.data;


import javax.annotation.Generated;

import me.lty.data.tables.Main;


/**
 * Convenience access to all tables in test
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table test.main
	 */
	public static final Main MAIN = me.lty.data.tables.Main.MAIN;
}
