/**
 * This class is generated by jOOQ
 */
package me.ele.data.tables.records;


import javax.annotation.Generated;

import me.ele.data.tables.Main;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MainRecord extends UpdatableRecordImpl<MainRecord> implements Record2<Integer, String> {

	private static final long serialVersionUID = 2066352203;

	/**
	 * Setter for <code>test.main.number</code>.
	 */
	public void setNumber(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>test.main.number</code>.
	 */
	public Integer getNumber() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>test.main.address</code>.
	 */
	public void setAddress(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>test.main.address</code>.
	 */
	public String getAddress() {
		return (String) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Integer, String> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Integer, String> valuesRow() {
		return (Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Main.MAIN.NUMBER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Main.MAIN.ADDRESS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getNumber();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getAddress();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MainRecord value1(Integer value) {
		setNumber(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MainRecord value2(String value) {
		setAddress(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MainRecord values(Integer value1, String value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached MainRecord
	 */
	public MainRecord() {
		super(Main.MAIN);
	}

	/**
	 * Create a detached, initialised MainRecord
	 */
	public MainRecord(Integer number, String address) {
		super(Main.MAIN);

		setValue(0, number);
		setValue(1, address);
	}
}
